config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get "up" => "rails/health#show", as: :rails_health_check

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    env['warden'].authenticate!

    if env['warden'].authenticated?
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    env['warden'].logout
    redirect_to root_path, notice: 'Logged out successfully'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User created successfully'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WardenAuthApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to 'Sign up', new_user_path %> |
      <%= link_to 'Login', new_session_path %> |
      <%= link_to 'Logout', session_path, method: :delete if request.env['warden'].authenticated? %>
    </nav>

    <% if flash[:notice] %>
      <div class="flash notice"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="flash alert"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <% if flash[:alert] %>
    <div class="flash alert"><%= flash[:alert] %></div>
  <% end %>

  <%= form_with model: @user, local: true do |form| %>
    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email, placeholder: "Enter your email" %>
    </div>

    <div>
      <%= form.label :password %><br>
      <%= form.password_field :password, placeholder: "Enter your password" %>
    </div>

    <div>
      <%= form.label :password_confirmation %><br>
      <%= form.password_field :password_confirmation, placeholder: "Confirm your password" %>
    </div>

    <div>
      <%= form.submit 'Sign up' %>
    </div>
  <% end %>

  <div class="links">
    <%= link_to 'Login', new_session_path %>
  </div>
</div>